## Configuration options to run Autoencoder.py
epochs: 10

image_size: 256
input_dir: "/fhome/mapsiv/QuironHelico/CroppedPatches"

model_name: "CNN_AUTOENCODER"
optimizer_name: "ADAM"
lr: 0.001
schedule_name: "ReduceLROnPlateau"

network: 
  checkpoint: /fhome/gia07/project/runs/run1/weights/CNN_autoencoder_epoch_4.pth

datasets: 
  neg_samples_dir: '/fhome/gia07/project/Train_test_splits/neg_samples.pkl'
  spit: False

  train_split: 0.72
  test_split: 0.2
  val_split: 0.08

  train: 
    batch_size: 1600

  test:
    path_folder: "/fhome/mapsiv/QuironHelico/CroppedPatches"
    path_pickle: "/fhome/gia07/project/Train_test_splits/test_data.pkl"

    batch_size: 1


