#!/bin/bash
#SBATCH -A atfg # Number of cores
#SBATCH -n 2 # Number of cores
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -D /fhome/gia07/Medical_Gia07/project/MSG_ERRORS # working directory
#SBATCH -p tfg # Partition to submit to
#SBATCH --mem 2048 # 2GB solicitados.
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
#SBATCH --gres gpu:1 # Para pedir gráficas

# if sbatch Autoencoder "test_name" 1 0 -> train 
# if sbatch Autoencoder "test_name" 0 1 -> test
# if sbatch Autoencoder "test_name" 1 1 -> train and test
# if sbatch Autoencoder "test_name" 2 0 -> generate images

