## Configuration options to run train.py
epochs: 100
patience: 100

model_name: "Word_level_predictor"
lr: 0.01
teacher_forcing_ratio: 0.05
scheduler: "CosineAnnealingWarmRestarts"
eta_min: 0.00005
T_m: 1
T_0: 100

network: 
  checkpoint: ~

datasets: 
  train: 
    batch_size: 64
    shuffle: True
    num_workers: 2

  valid:
    batch_size: 80
    shuffle: True
    num_workers: 2

  test:
    batch_size: 80
    shuffle: False
    num_workers: 2


