## Configuration options to run train.py
epochs: 50
patience: 7

model_name: "Word_level_predictor"
lr: 0.000005

network: 
  checkpoint: ~

datasets: 
  train: 
    batch_size: 32
    shuffle: True
    num_workers: 2

  valid:
    batch_size: 35
    shuffle: False
    num_workers: 2

  test:
    batch_size: 35
    shuffle: False
    num_workers: 2


