## Configuration options to run train.py
epochs: 100
patience: 100

model_name: "Word_level_predictor"
lr: 0.0001
teacher_forcing_ratio: 0.3
scheduler: "CosineAnnealingWarmRestarts"
eta_min: 0.000005
T_m: 1
T_0: 20

network: 
  checkpoint: ~

datasets: 
  train: 
    batch_size: 128
    shuffle: True
    num_workers: 2

  valid:
    batch_size: 35
    shuffle: True
    num_workers: 2

  test:
    batch_size: 35
    shuffle: False
    num_workers: 2


