## Configuration options to run train.py
epochs: 100
patience: 100

model_name: "Baseline"
lr: 0.0001
teacher_forcing_ratio: 0.3
scheduler: CosineAnnealingLR
T_max: 10
eta_min: 0.00001
network: 
  checkpoint: ~

datasets: 
  train: 
    batch_size: 4
    shuffle: True
    num_workers: 2

  valid:
    batch_size: 4
    shuffle: True
    num_workers: 2

  test:
    batch_size: 4
    shuffle: False
    num_workers: 2


