#!/bin/bash
#SBATCH -A atfg # Number of cores
#SBATCH -n 2 # Number of cores
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -D /fhome/gia07/Image_captioning/MSG_ERRORS # working directory
#SBATCH -p tfg # Partition to submit to
#SBATCH --mem 2048 # 2GB solicitados.
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
#SBATCH --gres gpu:1 # Para pedir gráficas

# Es el mateix que el altre pero per lo del lstm per si algu estaba provant algo
python3 /fhome/gia07/Image_captioning/src/lstm_train.py --test_name $1